[package]
name = "baseconverter"
version = "0.1.0"
authors = ["Livan Ojito <livanojito@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored="2.0.0"